Repository PranavBarthwal/cosmoXplore, pull requests merged in 2024-05, with the labels that each got.

#105 Typing Effect is Breaking the Word Wrap
  index.html
Labels: gssoc, level1

#134 [NEW FEATURE] : Multi-Camera Mars Rover Image Viewer
  app.js
  index.html
  style.css
Labels: gssoc, level3

#232 fix: Typing Effect is Breaking the Word Wrap
  src/App.css
  src/components/ErrorBoundary.jsx
  src/components/Hero/Hero.jsx
  src/index.css
Labels: gssoc, level2

#269 feat: A Custom Alert Pop up
  src/App.jsx
  src/assets/correct.svg
  src/assets/wrong.png
  src/components/ContactForm/ContactForm.jsx
  src/components/MarsRover/MarsRover.jsx
  src/components/Navbar/Navbar.jsx
  src/components/Toast/Toast.jsx
  src/components/Toast/Toast.module.css
  vite.config.js
Labels: gssoc, level2

#308 Improving the project's Fetching time
  src/pages/NasaProjects/NasaProjects.jsx
Labels: gssoc, level2, Apis_enhancement

#303 Fixed code to enhance dynamic feature code for year issue #291
  src/components/Footer/Footer.jsx
Labels: gssoc, level1

#302 [Doc]: Update Readme to add Environment Variables.
  .env.demo
  README.md
  src/components/BackGround/BackGround.jsx
  src/components/BackGround/BackGround.module.css
  src/components/Background/BackGround.module.css
Labels: gssoc, level1
