Repository PranavBarthwal/cosmoXplore, pull requests merged in 2024-06, with the labels that each got.

#355 [fix] : Website Main page background colour
  src/main.jsx
  src/pages/404 Page/Notfound.css
Labels: gssoc, level1

#357 [Bug]:Fix Navbar and Responsiveness
  src/components/Apod/Apod.jsx
  src/components/Apod/Apod.module.css
  src/components/ContactForm/ContactForm.jsx
  src/components/ContactForm/ContactForm.module.css
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/navabar.css
Labels: gssoc, level3

#382 feat: Enhancing Nav Bar
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.jsx
Labels: gssoc, level2

#428 Bug 🐞 Routing Navigation Error "404 Page Not Found" After Refreshing Pages
  src/components/Navbar/Navbar.jsx
  src/main.jsx
  vercel.json
Labels: gssoc, level3, ui_enhancement, Apis_enhancement

#433 Re-styled the "Vertical Scrollbar" Matching to "Website Design" Theme
  src/index.css
Labels: gssoc, level1
